module.exports = {
  up: (queryInterface, Sequelize) => queryInterface.bulkInsert('cashiers',
    [
      {
        number: 1,
        type: 'preferencial',
        status: 'ativo',
        storeId: 1,
        createdAt: new Date(2019, 0, 5, 12, 00),
        updatedAt: new Date(2019, 0, 5, 12, 00),
      },
      {
        number: 3,
        type: 'caixa rápido',
        status: 'ativo',
        storeId: 1,
        createdAt: new Date(2019, 0, 5, 12, 00),
        updatedAt: new Date(2019, 0, 5, 12, 00),
      },
      {
        number: 2,
        type: 'comum',
        status: 'ativo',
        storeId: 1,
        createdAt: new Date(2019, 0, 5, 12, 00),
        updatedAt: new Date(2019, 0, 5, 12, 00),
      },
      {
        number: 2,
        type: 'comum',
        status: 'ativo',
        storeId: 2,
        createdAt: new Date(2019, 0, 5, 12, 00),
        updatedAt: new Date(2019, 0, 5, 12, 00),
      },
      {
        number: 4,
        type: 'caixa rápido',
        status: 'ativo',
        storeId: 1,
        createdAt: new Date(2019, 0, 5, 12, 00),
        updatedAt: new Date(2019, 0, 5, 12, 00),
      },
      {
        number: 5,
        type: 'caixa rápido',
        status: 'ativo',
        storeId: 1,
        createdAt: new Date(2019, 0, 5, 12, 00),
        updatedAt: new Date(2019, 0, 5, 12, 00),
      },
      {
        number: 6,
        type: 'preferencial',
        status: 'ativo',
        storeId: 1,
        createdAt: new Date(2019, 0, 5, 12, 00),
        updatedAt: new Date(2019, 0, 5, 12, 00),
      },
      {
        number: 7,
        type: 'preferencial',
        status: 'ativo',
        storeId: 1,
        createdAt: new Date(2019, 0, 5, 12, 00),
        updatedAt: new Date(2019, 0, 5, 12, 00),
      },
      {
        number: 1,
        type: 'caixa rápido',
        status: 'ativo',
        storeId: 2,
        createdAt: new Date(2019, 0, 5, 12, 00),
        updatedAt: new Date(2019, 0, 5, 12, 00),
      },
      {
        number: 3,
        type: 'caixa rápido',
        status: 'ativo',
        storeId: 2,
        createdAt: new Date(2019, 0, 5, 12, 00),
        updatedAt: new Date(2019, 0, 5, 12, 00),
      },
      {
        number: 4,
        type: 'preferencial',
        status: 'ativo',
        storeId: 2,
        createdAt: new Date(2019, 0, 5, 12, 00),
        updatedAt: new Date(2019, 0, 5, 12, 00),
      },
      {
        number: 5,
        type: 'preferencial',
        status: 'ativo',
        storeId: 2,
        createdAt: new Date(2019, 0, 5, 12, 00),
        updatedAt: new Date(2019, 0, 5, 12, 00),
      },
      {
        number: 1,
        type: 'caixa rápido',
        status: 'ativo',
        storeId: 3,
        createdAt: new Date(2019, 0, 5, 12, 00),
        updatedAt: new Date(2019, 0, 5, 12, 00),
      },
      {
        number: 2,
        type: 'caixa rápido',
        status: 'ativo',
        storeId: 3,
        createdAt: new Date(2019, 0, 5, 12, 00),
        updatedAt: new Date(2019, 0, 5, 12, 00),
      },
      {
        number: 3,
        type: 'preferencial',
        status: 'ativo',
        storeId: 3,
        createdAt: new Date(2019, 0, 5, 12, 00),
        updatedAt: new Date(2019, 0, 5, 12, 00),
      },
      {
        number: 4,
        type: 'preferencial',
        status: 'ativo',
        storeId: 3,
        createdAt: new Date(2019, 0, 5, 12, 00),
        updatedAt: new Date(2019, 0, 5, 12, 00),
      },
    ]),

  down: (queryInterface, Sequelize) => (queryInterface.dropTable('cashiers')),
};
