module.exports = {
  up: (queryInterface, Sequelize) => queryInterface.bulkInsert('orders',
    [
      {
        status: 'cancelado',
        orderDate: new Date(),
        deliveryDate: new Date(),
        userId: 1,
        supplierId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        status: 'entregue',
        orderDate: new Date(),
        deliveryDate: new Date(),
        userId: 1,
        supplierId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        status: 'entregue',
        orderDate: new Date(2019, 2, 5),
        deliveryDate: new Date(2019, 2, 15),
        userId: 1,
        supplierId: 1,
        createdAt: new Date(2019, 2, 5),
        updatedAt: new Date(),
      },
      {
        status: 'entregue',
        orderDate: new Date(2019, 2, 5),
        deliveryDate: new Date(2019, 2, 15),
        userId: 2,
        supplierId: 2,
        createdAt: new Date(2019, 2, 5),
        updatedAt: new Date(),
      },
      {
        status: 'entregue',
        orderDate: new Date(2019, 2, 5),
        deliveryDate: new Date(2019, 2, 15),
        userId: 3,
        supplierId: 3,
        createdAt: new Date(2019, 2, 5),
        updatedAt: new Date(),
      },
      {
        status: 'a caminho',
        orderDate: new Date(2019, 11, 5),
        deliveryDate: new Date(2020, 0, 1),
        userId: 3,
        supplierId: 3,
        createdAt: new Date(2019, 11, 5),
        updatedAt: new Date(),
      },
      {
        status: 'confirmado',
        orderDate: new Date(2019, 11, 5),
        deliveryDate: new Date(2020, 0, 5),
        userId: 3,
        supplierId: 2,
        createdAt: new Date(2019, 11, 5),
        updatedAt: new Date(),
      },
      {
        status: 'cancelado',
        orderDate: new Date(2019, 15, 5),
        deliveryDate: new Date(2020, 0, 5),
        userId: 3,
        supplierId: 1,
        createdAt: new Date(2019, 15, 5),
        updatedAt: new Date(),
      },
    ]),

  down: (queryInterface, Sequelize) => (queryInterface.dropTable('orders')),
};